---
# Used to manage images that reference registry.redhat.io which requires authentication
# Pull secret is retrieved from the openshift namespace on a given cluster and can be set in each product namespace to pull images
# Must be overriden for OSD where the pull_secret_name should be set to registry-redhat-io-dockercfg
pull_secret_name: imagestreamsecret

# The name of the image pull secret which will be created in the product namespace
# This will be overriden depending on the product using this role
# Fuse will override this to ensure that the secret created in the shared/managed fuse is syndesis-pull-secret
product_ns_pull_secret_name: imagestreamsecret