---
- name: Create Service Monitor resource
  shell: "oc apply -f {{ item }} -n {{ ups_namespace }}"
  with_items: "{{ ups_svc_monitor_resources }}"
  register: output
  failed_when: output.stderr != '' and 'already exists' not in output.stderr

- name: Copy UPS monitor templates
  template:
    src: "{{ item }}.yml.j2"
    dest: "{{ ups_template_dir }}/{{ item }}.yml"
  with_items: "{{ ups_svc_monitor_templates }}"

- name: Create UPS monitor resources
  shell: "oc apply -f {{ ups_template_dir }}/{{ item }}.yml -n {{ ups_namespace }}"
  with_items: "{{ ups_svc_monitor_templates }}"
  register: output
  failed_when: output.stderr != '' and 'already exists' not in output.stderr

- name: Delete UPS monitor temporary files
  file:
    path: "{{ ups_template_dir }}/{{ item }}.yml"
    state: absent
  with_items: "{{ ups_svc_monitor_templates }}"