---
- name: "update booster catalog to latest release"
  shell: "oc patch configmap launcher -n {{ launcher_namespace }} --type=merge --patch='{\"data\": {\"launcher.backend.catalog.git.ref\": \"{{ launcher_catalog_git_ref }}\"}}'"
  register: launcher_patch
  failed_when: launcher_patch.stderr != '' and 'not patched' not in launcher_patch.stderr
  changed_when: launcher_patch.rc == 0
