---
- name: Delete limit range (if exists)
  shell: oc delete limitrange 3scale-core-resource-limits -n {{ threescale_namespace }}
  register: delete_limits_cmd
  failed_when: delete_limits_cmd.stderr != '' and 'not found' not in delete_limits_cmd.stderr

- name: Apply resource overrides for 3scale
  include_role:
    name: resource_limits
  vars:
    ns: "{{ threescale_namespace }}"
    resources: "{{ threescale_resources }}"
