---
- import_playbook: "./prerequisites.yml"
- import_playbook: "./openshift.yml"

- hosts: master
  gather_facts: no
  tasks:
    - include_role:
        name: mdc
        tasks_from: cors.yml
      vars:
        openshift_master_url: "{{ hostvars['EVAL_VARS']['openshift_master_url'] | replace('https://', '') }}"
      when:    
        - run_master_tasks | default(true) | bool
        - mdc | default(true) | bool
    
    - name: restart openshift master services
      shell: "/usr/local/bin/master-restart {{ item }}"
      become: yes
      with_items:
        - api
        - controllers
      when:
        - run_master_tasks | default(true) | bool 
        - mdc | default(true) | bool

    - name: check if openshift master services are running
      shell: oc get nodes
      register: task_result
      until: task_result.rc == 0
      retries: 6
      delay: 5
      failed_when: task_result.rc != 0
      when:
        - run_master_tasks | default(true) | bool 
        - mdc | default(true) | bool